### ISSUE TITLE
max_payload can this be an environment variable

### ISSUE THREAD

**Issue by lucidprogrammer** [nats-io/nats-streaming-docker#11]
We can keep max_payload value in a file and provide via --stan_config. Is it possible to provide it as an environment variable. That facility will be neat if possible

**Comment by kozlovic** [comment]
Not, this is not possible. More over, this is a property of NATS, not streaming, so the change would have to be done in NATS or have it in streaming, but again, this is for the NATS (when embedded).
Although I understand the value of env variables, implementing the change just for this one would open the door to all others, and there are quite a bit... ;-)
