### ISSUE TITLE
NATS Streaming docker image don't ship with Root CA certificates

### ISSUE THREAD

**Issue by 3asm** [nats-io/nats-streaming-docker#19]
Hi,

Thanks for the amazing work on NATS.

We are trying to use NATS Streaming with TLS using a Let's Encrypt certificate.

It took quite some time to figure out that NATS streaming is failing to connect to a remote NATS server over TLS because the image don't ship with CA Certificates.

The Docker image of NATS server is based on Alpine and installs the CA certificates.

The following is a sample of a modified NATS image that uses the releases of NATS streaming.

```Dockerfile
FROM alpine:3.11

ENV NATS_SERVER 0.17.0

RUN set -eux; \
	apkArch="$(apk --print-arch)"; \
	case "$apkArch" in \
		arm64) natsArch='arm64' ;; \
		armhf) natsArch='arm6' ;; \
		armv7) natsArch='arm7' ;; \
		x86_64) natsArch='amd64' ;; \
		x86) natsArch='386' ;; \
		*) echo >&2 "error: $apkArch is not supported!"; exit 1 ;; \
	esac; \
	\
	wget -O nats-streaming-server.zip "https://github.com/nats-io/nats-streaming-server/releases/download/v${NATS_SERVER}/nats-streaming-server-v${NATS_SERVER}-linux-${natsArch}.zip"; \
	\
	apk add --no-cache ca-certificates; \
	apk add --no-cache --virtual buildtmp unzip; \
	\
	unzip nats-streaming-server.zip "nats-streaming-server-v${NATS_SERVER}-linux-${natsArch}/nats-streaming-server"; \
	rm nats-streaming-server.zip; \
	mv "nats-streaming-server-v${NATS_SERVER}-linux-${natsArch}/nats-streaming-server" /usr/local/bin; \
	rmdir "nats-streaming-server-v${NATS_SERVER}-linux-${natsArch}"; \
	\
	apk del --no-cache --no-network buildtmp

COPY stan.conf /etc/nats/nats-server.conf
EXPOSE 4222 8222 6222
CMD ["nats-streaming-server"]
```

Does it make sense to homogenize both images and add CA certificates to avoid failing TLS connections?

**Comment by kozlovic** [comment]
We had plan to adopt the docker image build process from https://github.com/nats-io/nats-docker but did not find the time yet.

**Comment by kozlovic** [comment]
We have moved to the same layout than the one for NATS Server and now provide an alpine based image. See https://github.com/nats-io/nats-streaming-docker/pull/21. Closing this issue.
