### ISSUE TITLE
FROM alpine:latest instead FROM scratch?

### ISSUE THREAD

**Issue by zshamrock** [nats-io/nats-streaming-docker#4]
Based on https://hub.docker.com/r/logimethods/stan/~/dockerfile/, it uses 

`FROM alpine:latest` instead of
`FROM scratch` due to https://github.com/docker/docker/issues/23865
 
Not sure if it is still relevant, but worth to double check.

**Comment by kozlovic** [comment]
This is not an official image from Apcera, but from someone in the community. As indicated in the other issue, we have submitted a PR for the official image.
