### ISSUE TITLE
Stop using deprecated Windows 2016 hosted runners

### ISSUE THREAD

**Issue by philpennock** [nats-io/nats-streaming-docker#41]
Per email from GitHub:

> On March 15, 2022, Windows 2016 hosted runners will be [removed from GitHub Actions](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/).
> 
> In preparation for the deprecation, there are two scheduled brownout periods for our team to perform maintenance:
>   * December 1, 2021: 4:00pm–10:00pm UTC
>   * February 7, 2022: 4:00pm–10:00pm UTC
> 
> Jobs that use Windows 2016 scheduled to run during this time will temporarily fail.
> 
> **What you need to do**
> We recommend you change jobs using `runs-on: windows-2016` to use `runs-on: windows-latest`  which will ensure you're always running on the latest version of Windows Server.

File `.github/workflows/main.yaml` defines a Job `windows-2016` which is `runs-on: windows-2016`.

**Comment by kozlovic** [comment]
Closing this since it was resolved in #42
