### ISSUE TITLE
Upgrade go version

### ISSUE THREAD

**Issue by riaan53** [nats-io/nats-streaming-docker#5]
Hi, I see the official images (this and normal nats) are build with go1.6.3. Using go1.7 reduces CPU load (a lot) at higher message rates. Do you plan to update the images?

Thanks!

**Comment by kozlovic** [comment]
@riaan53 With go 1.7, `go vet` panics, and reports some warnings on tls, so we need to investigate more. There will be other things that will be added in the near future I suspect, so we can get issue a new release with go 1.7.

**Comment by kozlovic** [comment]
Correction: the panic is due to presence of `go/pkg` with builds from previous version. We still have some warnings to look at though.

**Comment by riaan53** [comment]
Sounds good!  thx. Will close this issue then.
