### ISSUE TITLE
Please add official HA Kubernetes helm chart

### ISSUE THREAD

**Issue by AceHack** [nats-io/nats-streaming-docker#9]
Would be great to start with the linux version but the windows version would be great to come 2nd.  Also I recommend using either Statefulsets and/or the operator pattern for best HA results.

Thanks.

**Comment by ColinSullivan1** [comment]
@AceHack , work is underway, we'll let you know when it is ready.  

https://github.com/ColinSullivan1/nats-k8s/tree/master/charts

**Comment by wallyqs** [comment]
@llonchj sharing a helm chart for streaming next week, will update here once available

**Comment by koalalorenzo** [comment]
Any update on publishing it in the kubernetes/helm charts?

**Comment by ColinSullivan1** [comment]
@bkleef , @koalalorenzo , Thanks for pinging us.  We are looking into developing a NATS streaming server operator, similar to https://github.com/nats-io/nats-operator.

**Comment by koalalorenzo** [comment]
_kinda cool_, what about people that don't want to run an operator? :-)  

( _Do they have to pray the gods to change the rules of physic and reduce the satellite latency for ships_? 😆 )

**Comment by abh** [comment]
> kinda cool, what about people that don't want to run an operator? :-)
> 
Isn’t helm basically a generic operator using a bunch of cutnpasta templates?

If you don’t want an operator you can build your manifests today. If you want automation a proper operator is the way to go.

**Comment by koalalorenzo** [comment]
This issue is about helm charts :) 
Let's keep the discussion as well as the request around Helm Charts.

**Comment by wallyqs** [comment]
Hi, we did take a look at trying to create Helm charts for NATS Streaming but there were a few limitations in creating a cluster using only Helm features that would be better solved with the operator approach instead, like being able to assign an explicit name to each Pod a priori when creating the cluster (meaning that each Pod starts with one different flag in the command line so can't use a Deployment), or ensure that there is an odd number of pods in the raft cluster to
avoid partitions for example.

Here is a repo where there are Helm charts for NATS Streaming which could help to get things started using an extra Pod for bootstrapping plus a Deployment of Pods that start as followers, but currently not planning on making it part of official charts and will instead take the operator approach:
https://github.com/wallyqs/nats-streaming-cluster-chart

**Comment by koalalorenzo** [comment]
Plz, don't close this issue: have an official one would help a lot!

**Comment by kozlovic** [comment]
There is also a NATS Streaming Operator Helm Chart here: https://github.com/nats-io/nats-streaming-operator/tree/master/helm/nats-streaming-operator

Closing this.
